# Docker role: roles/docker.yml
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Install Docker dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl']
    state: present
    update_cache: yes

- name: Download Docker GPG key and place it in keyrings directory
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.asc 
    mode: '0644'
    force: true 
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present 
  become: yes

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
  become: yes