# Docker role: roles/docker.yml
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Install Docker dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg']
    state: present
    update_cache: yes

- name: Download Docker GPG key and place it in keyrings directory
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg  # Або /ubuntu/gpg, залежно від ОС
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
    force: true

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
  become: yes